# Sobre MetaDocencia {#intro}

## Mision y Visión

### Visión

Somos una comunidad inclusiva y colaborativa que mejora la educación potenciando docentes de países menos favorecidos.

### Misión

Somos una organización sin fines de lucro que nutre una comunidad docente hispanohablante enseñando métodos educativos concretos, basados en evidencia y centrados en tus estudiantes. Desarrollamos colaborativamente recursos abiertos, reutilizables y accesibles para fomentar prácticas de enseñanza eficaces.

## Código de Conducta

Con el objetivo de fomentar un ambiente abierto, seguro y amigable, quienes organizamos nos comprometemos a hacer de la participación en MetaDocencia una experiencia libre de acoso para  todas las personas, independientemente del sexo, identidad, género, edad, orientación sexual, discapacidad, apariencia física, tamaño corporal, nacionalidad, raza, etnia, religión (o la falta de ella), ideología u opciones tecnológicas. 

### Nuestros estándares

No toleramos el acoso de quienes participan en MetaDocencia de ninguna forma. 

#### Ejemplos de comportamiento que contribuyen a crear un ambiente positivo para nuestra comunidad:

* Demostrar empatía y amabilidad ante otras personas
* Respeto a diferentes opiniones, puntos de vista y experiencias
* Dar y aceptar adecuadamente retroalimentación constructiva
* Aceptar la responsabilidad y disculparse ante quienes afectemos por nuestros errores, aprendiendo de la experiencia
* Centrarse en lo que sea mejor no sólo para nosotros como personas, sino para la comunidad en general

#### Ejemplos de comportamiento inaceptable:

* El uso de lenguaje o imágenes sexualizadas como también atención o avances sexuales no deseados
* Comentarios despectivos (trolling), insultantes y ataques personales o políticos
* Cualquier tipo de acoso en público o privado
* Publicar información privada de otras personas, tales como direcciones físicas o de correo   electrónico, sin su permiso explícito
* Otras conductas que puedan ser razonablemente consideradas como inapropiadas en un entorno profesional

### Nuestras responsabilidades

Quienes hacemos MetaDocencia somos responsables de aclarar los estándares de comportamiento aceptable y nos reservamos el derecho de admisión o permanencia, temporal o permanente, en la comunidad de MetaDocencia para cualquier caso de comportamiento que consideremos inaceptable.

También tenemos la responsabilidad y nos reservamos el derecho de eliminar, editar o rechazar comentarios, materiales y otras contribuciones que no estén alineadas con este Código de Conducta. 

### Alcance

Este código de conducta aplica a todos los espacios relacionados con MetaDocencia. Esto incluyen nuestra cuenta de correo electrónico, nuestro Slack, nuestra organización en GitHub y todos sus repositorios, nuestros talleres a través de Zoom y cualquier otro medio que sea parte de MetaDocencia.

### Aplicación

Los casos de comportamiento abusivo, acosador o inaceptable pueden ser informados enviando un correo electrónico a [metadocencia@gmail.com](mailto:metadocencia@gmail.com). Todas los mensajes serán revisados e investigados y darán como resultado la respuesta la respuesta que consideremos necesaria y apropiada a las circunstancias. 

Quienes fundamos MetaDocencia respetaremos la privacidad y la seguridad de quienes reporten incidentes.

### Atribución

Este Código de Conducta es una adaptación del [Contributor Covenant](https://www.contributor-covenant.org), versión 2.0,
disponible en https://www.contributor-covenant.org/es/version/2/0/code_of_conduct.html

### Uso

El código de conducta está publicado y accesible en diferentes espacios de MetaDocencia, como el sitio web y el repositorio de GitHub.  También se menciona y se recuerda el mismo al inicio de todos los cursos de MetaDocencia.


## Licencia

Los materiales que cuentan con una licencia permiten ser utilizados correctamente.  Si la licencia no figura explicitamente, por defecto el contenido es cerrado. 

Sugerimos seleccionar una licencia abierta tanto para el material (texto, imágenes, videos) como para el software. 

### Material

Las licencias [Creative Commons](http://www.creativecommons.org.ar/licencias.html) proveen diversos tipos  dependiendo de lo que deseamos que pueda hacer quien use nuestros materiales. Este [selector de licencias](https://creativecommons.org/choose/?lang=es_AR) puede ayudarnos a elegir la licencia que mejor se adapta a nuestras necesidades. 

MetaDocencia utiliza la licencia **Creative Commons Atribución/Reconocimiento-NoComercial 4.0 Licencia Pública Internacional — CC BY-NC 4.0** a menos que utilicemos un material que solicita utilizar otra licencia.  Esta licencia está explicita en el sitio web, en los repositorios de github y en los materiales correspondientes, como por ejemplo los videos o las slides de las presentaciones. 

### Software

Para el software, existen múltiples opciones. Les presentamos tres opciones:

* La [licencia MIT](https://opensource.org/licenses/MIT), que permite que los usuarios le den cualquier uso que quieran al código.

* Usar la [Licencia Pública General de GNU (GPL)](https://www.gnu.org/licenses/licenses.es.html#GPL), que también permite a los usuarios hacer cualquier uso que quieran exigiendo que compartan su propio código bajo esta licencia.

* La [licencia hipocrática](https://firstdonoharm.dev/version/2/1/license.html), que permite usar el código libremente siempre que el uso no viole los tratados básicos de derechos humanos.  

Tengamos en cuenta que si utilizamos código de otros autores pueden existir restricciones con respecto a que licencia podemos asignar a nuestro propio código.

## Estructura

MetaDocencia tiene una estructura de funcionamiento por medio de equipos de trabajo por temática y por roles de toma de decisiones.

Los tres grupos principales son el Core Team, el Advisory Team y les Colaboradores.  Dentro de los colaboradores se cuentan con equipos de: Accesibilidad, Comunicación, Reportes y Desearrollo de contenidos.



## Gobernanza
## Contribuir
